[SQUASH] yaap: Add framework compatibility matrix for Lineage HALs.
 * Cover all possible Lineage HALs here instead of covering
   them in the device specific manifests.

Change-Id: Id7f7d6eb1f14190a061537cebfabd339af9b1620

config: device_framework_matrix: Remove inscreen and power HAL entries

These don't exist anymore.

Change-Id: If7e3a7719cba03c6df0510e2bdbfb080da1f1880

lineage: framework_manifest: declare support for IHighTouchPollingRate

Change-Id: Id14ec4df916028747023277982e897c2015a496c

config: device_framework_matrix: Add vendor.lineage.health

Change-Id: I91ee2a15ee2f68947f220ab6e885b9049936acb2

config: Move IAntiFlicker to fqname

Fixes:
ERROR: HIDL interface vendor.lineage.livedisplay@2.0::IAntiFlicker is
referenced in /system/etc/vintf/compatibility_matrix.device.xml,
but there is no corresponding .hal definition associated with a
hidl_interface module in this build. Typo?

Change-Id: If7708540351db6f465504ed433638653e2c52503

Change-Id: I7198a27cbf4a46b9ea009df4b02830fa1c94d278

config: Remove deprecated vendor.lineage.trust from FCM

Change-Id: Ie5c05b460015c38895df56292a5670ca6dad17e6

config: device_framework_matrix: Add lineage.hardware.radio.config

Change-Id: I013f75d64b5d909c45e3f876f8e46f9958a728b9